stages:
  - code-check
  - tests
  - benchmark

code-check:
  stage: code-check
  script:
    - cd testing
    - tox -e code-check

tests:
  stage: tests
  image: leapcode/soledad:latest
  services:
    - couchdb
  script:
    - cd testing
    - tox -- --couch-url http://couchdb:5984

benchmark:
  stage: benchmark
  image: leapcode/soledad:latest
  services:
    - couchdb
  script:
    - cd testing
    - tox -e perf -- --couch-url http://couchdb:5984
  tags:
    - docker
    - benchmark
